{% set name = "psij-python" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psij-python-{{ version }}.tar.gz
  sha256: a037bde868d9e3dd6d02f21593148694f6ddb5a6b53cf8ec558418cb51b958d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - filelock >=3.4,<4.dev0
    - psutil >=5.9,<6.dev0
    - pystache >=0.6.0
    - typeguard >=2.12,<3.dev0
    - typing-compat

test:
  imports:
    - psij
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/exaworks/psij-python
  summary: This is an implementation of the PSI/J (Portable Submission Interface for Jobs) specification.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/exaworks/psij-python
  doc_url: https://exaworks.org/psij-python/#docs

extra:
  recipe-maintainers:
    - xylar
    - jan-janssen
