{% set name = "psij-python" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psij-python-{{ version }}.tar.gz
  sha256: 336455634af2fdb34bbb77dceebbb384833bedffef68c3d36eb25a4dcfc1b104

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - filelock >=3.4,<4.dev0
    - psutil >=5.9,<6.dev0
    - pystache >=0.6.0
    - typeguard >=2.12,<3.dev0
    - pystache >=0.6.0

test:
  imports:
    - psij
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/exaworks/psij-python
  summary: This is an implementation of the PSI/J (Portable Submission Interface for Jobs)         specification.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - jan-janssen
