{% set name = "psij-python" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psij-python-{{ version }}.tar.gz
  sha256: 6fcecd3fb9f33e8a8bd370ba4eb21e10ecc306524f0823f4fe85c99a8e2d1693

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - filelock >=3.4,<4.dev0
    - psutil >=5.9,<6.dev0
    - pystache >=0.6.0
    - typeguard >=2.12,<3.dev0
    - pystache >=0.6.0

test:
  imports:
    - psij
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/exaworks/psij-python
  summary: This is an implementation of the PSI/J (Portable Submission Interface for Jobs)         specification.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - username
    - jan-janssen
