{% set name = "psij-python" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psij-python-{{ version }}.tar.gz
  sha256: 063ee36d7450d50a977fb30a59180f7103423f4f49ef7ce3373b2031ace097cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - filelock >=3.4,<4.dev0
    - packaging >=24.0,<25.dev0
    - psutil >=5.9,<6.dev0
    - pystache >=0.6.0
    - typeguard >=2.12,<3.dev0
    - typing-compat

test:
  imports:
    - psij
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/exaworks/psij-python
  summary: This is an implementation of the PSI/J (Portable Submission Interface for Jobs) specification.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/exaworks/psij-python
  doc_url: https://exaworks.org/psij-python/#docs

extra:
  recipe-maintainers:
    - xylar
    - jan-janssen
